name: Deploy to GitHub Pages

on:
  # 每次推送到 main 分支时触发部署
  push:
    branches: [ main ]
  # 允许你从 GitHub 网页端手动触发部署
  workflow_dispatch:

# 允许脚本部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # 注意：如果你本地是用 npm 安装依赖的，这里不用改。
        # 如果你用的是 pnpm 或 yarn，请去掉下面两行的注释并修改为你用的包管理器
        # with:
          # package-manager: pnpm 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4